In [7]:
# Groupby on IPL Dataset

In [8]:
import pandas as pd

delivery = pd.read_csv('deliveries.csv')

In [9]:

delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [10]:
runs = delivery.groupby('batsman')

In [11]:
runs

In [12]:
runs['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
SK Raina          4548
V Kohli           4423
RG Sharma         4207
G Gambhir         4132
DA Warner         4014
RV Uthappa        3778
CH Gayle          3651
S Dhawan          3561
MS Dhoni          3560
AB de Villiers    3486
Name: batsman_runs, dtype: int64

In [13]:
masks = delivery['batsman_runs'] == 3
new_delivery = delivery[masks]

In [14]:
new_delivery
# new_delivery.shape[0]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
1090,5,2,Delhi Daredevils,Royal Challengers Bangalore,1,7,SW Billings,AP Tare,B Stanlake,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
1118,5,2,Delhi Daredevils,Royal Challengers Bangalore,6,4,SV Samson,SW Billings,B Stanlake,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
1626,7,2,Mumbai Indians,Kolkata Knight Riders,12,3,KH Pandya,N Rana,Kuldeep Yadav,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
1822,8,2,Kings XI Punjab,Royal Challengers Bangalore,4,3,M Vohra,HM Amla,SR Watson,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147265,623,1,Mumbai Indians,Delhi Daredevils,12,1,MJ Guptill,KH Pandya,S Nadeem,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
148730,629,2,Rising Pune Supergiants,Kings XI Punjab,15,6,MS Dhoni,NLTC Perera,AR Patel,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
149405,632,2,Royal Challengers Bangalore,Delhi Daredevils,6,2,KL Rahul,V Kohli,CH Morris,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
149659,633,2,Royal Challengers Bangalore,Gujarat Lions,9,1,AB de Villiers,STR Binny,SB Jakati,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
150090,635,1,Gujarat Lions,Sunrisers Hyderabad,20,5,DS Kulkarni,RA Jadeja,B Kumar,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN

In [15]:
new_delivery.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(10)

batsman
M Vijay           17
S Dhawan          16
G Gambhir         15
AM Rahane         14
DA Warner         13
AB de Villiers    12
RV Uthappa        12
MS Dhoni          11
V Kohli           11
MEK Hussey        11
Name: batsman_runs, dtype: int64

In [16]:
sixes_only = delivery[delivery['batsman_runs']==6]
sixes_only

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
75,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,13,2,Yuvraj Singh,MC Henriques,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150395,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,2,V Kohli,CH Gayle,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150428,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,15,5,SR Watson,KL Rahul,MC Henriques,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150440,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150453,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [17]:
res = sixes_only.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head()
res

batsman
CH Gayle     1596
SK Raina     1044
RG Sharma    1038
DA Warner     960
V Kohli       960
Name: batsman_runs, dtype: int64

In [18]:
four_only = delivery[delivery['batsman_runs']==4]
four_only

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
30,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,5,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
32,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,1,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150403,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,11,4,V Kohli,AB de Villiers,BCJ Cutting,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150407,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,2,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150418,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,1,KL Rahul,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150447,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,6,Sachin Baby,STR Binny,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [19]:
res = four_only.groupby('batsman')['batsman_runs'].size().sort_values(ascending=False)

In [20]:
res

batsman
G Gambhir     484
SK Raina      402
DA Warner     401
S Dhawan      401
V Kohli       384
             ...
AC Thomas       1
UA Birla        1
AG Murtaza      1
Umar Gul        1
VRV Singh       1
Name: batsman_runs, Length: 368, dtype: int64

In [21]:
cricket_team = delivery.groupby('batsman')
cricket_team.get_group('V Kohli')

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150410,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,5,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,0,0,0,V Kohli,bowled,NaN

In [22]:
# Step 1: Grouping
cricket_team = delivery.groupby('batsman')

# Step 2: Kohli ka data alag kiya
kohli_data = cricket_team.get_group('V Kohli')

# Step 3: Target column par sum lagaya
total_runs = kohli_data['batsman_runs'].sum()

print(total_runs)

4423

In [28]:
wide_run = delivery[delivery['wide_runs'] > 0]
wide_run.groupby('bowler')['wide_runs'].sum().sort_values(ascending=False).head(10)

bowler
P Kumar       144
SL Malinga    143
DW Steyn      105
DJ Bravo       93
B Kumar        90
UT Yadav       90
SR Watson      90
RP Singh       89
Z Khan         89
R Ashwin       88
Name: wide_runs, dtype: int64

In [29]:
# 1. Pehle mask banayein (Row filter)
mask = delivery['wide_runs'] > 0

# 2. Mask ke baad column ki list dein
specific_data = delivery[mask][['bowler', 'wide_runs']]

# Ab check karein
print(specific_data.head())

          bowler  wide_runs
4       TS Mills          2
78   A Choudhary          1
107  A Choudhary          1
108  A Choudhary          1
146      B Kumar          1

In [35]:
mera_mask = delivery['wide_runs']>0
print(mera_mask.head())

filtered_data = delivery[mera_mask][['bowler', 'wide_runs']]
filtered_data.head()

0    False
1    False
2    False
3    False
4     True
Name: wide_runs, dtype: bool

          bowler  wide_runs
4       TS Mills          2
78   A Choudhary          1
107  A Choudhary          1
108  A Choudhary          1
146      B Kumar          1

In [38]:
mask = delivery[delivery['wide_runs']>0]
group_run=mask.groupby('bowler')['wide_runs'].sum().sort_values(ascending=False).head()
print(group_run)

bowler
P Kumar       144
SL Malinga    143
DW Steyn      105
DJ Bravo       93
B Kumar        90
Name: wide_runs, dtype: int64

In [41]:
dhoni_data = delivery.groupby('batsman')
dhoni_data.get_group('MS Dhoni')

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
469,2,2,Rising Pune Supergiant,Mumbai Indians,16,4,MS Dhoni,SPD Smith,HH Pandya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
473,2,2,Rising Pune Supergiant,Mumbai Indians,17,2,MS Dhoni,SPD Smith,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
478,2,2,Rising Pune Supergiant,Mumbai Indians,18,1,MS Dhoni,SPD Smith,MJ McClenaghan,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
479,2,2,Rising Pune Supergiant,Mumbai Indians,18,2,MS Dhoni,SPD Smith,MJ McClenaghan,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
482,2,2,Rising Pune Supergiant,Mumbai Indians,18,5,MS Dhoni,SPD Smith,MJ McClenaghan,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148760,629,2,Rising Pune Supergiants,Kings XI Punjab,20,3,MS Dhoni,R Ashwin,AR Patel,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
148761,629,2,Rising Pune Supergiants,Kings XI Punjab,20,4,MS Dhoni,R Ashwin,AR Patel,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
148762,629,2,Rising Pune Supergiants,Kings XI Punjab,20,5,MS Dhoni,R Ashwin,AR Patel,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
148763,629,2,Rising Pune Supergiants,Kings XI Punjab,20,6,MS Dhoni,R Ashwin,AR Patel,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
148764,629,2,Rising Pune Supergiants,Kings XI Punjab,20,7,MS Dhoni,R Ashwin,AR Patel,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [53]:
all_batsman = delivery.groupby('batsman')

kholi = all_batsman.get_group('V Kohli')['batsman_runs'].sum()
dhoni = all_batsman.get_group("MS Dhoni")['batsman_runs'].sum()

print(f"Kohli: {kholi}, Dhoni: {dhoni}")

Kohli: 4423, Dhoni: 3560

In [54]:
# 1. Mask lagaya (Sirf in do players ka data)
mask = delivery['batsman'].isin(['V Kohli', 'MS Dhoni'])
dual_data = delivery[mask]

# 2. Groupby kar ke sum kiya
comparison = dual_data.groupby('batsman')['batsman_runs'].sum()

print(comparison)

batsman
MS Dhoni    3560
V Kohli     4423
Name: batsman_runs, dtype: int64

In [57]:
over = delivery[delivery['over']<=6]

batting_team = over.groupby('batting_team')['total_runs'].sum().sort_values(ascending=False)
print(batting_team)

batting_team
Mumbai Indians                 6946
Kings XI Punjab                6854
Kolkata Knight Riders          6755
Delhi Daredevils               6665
Royal Challengers Bangalore    6628
Chennai Super Kings            6021
Rajasthan Royals               5065
Sunrisers Hyderabad            3501
Deccan Chargers                3417
Pune Warriors                  1895
Gujarat Lions                  1559
Rising Pune Supergiant          785
Kochi Tuskers Kerala            680
Rising Pune Supergiants         638
Name: total_runs, dtype: int64

In [63]:
death_overs_data = delivery[delivery['over']>16]

top_death_batsmen = death_overs_data.groupby('batsman')['total_runs'].sum().sort_values(ascending=False).head()
print(top_death_batsmen)

batsman
MS Dhoni          1786
KA Pollard        1155
RG Sharma         1070
AB de Villiers     945
V Kohli            751
Name: total_runs, dtype: int64

In [64]:
total_run = delivery[delivery['total_runs']==0]

bw=total_run.groupby('bowler')['total_runs'].count().sort_values(ascending=False).head()

In [65]:
bw

bowler
P Kumar            1075
Harbhajan Singh    1062
SL Malinga         1060
DW Steyn            978
A Mishra            953
Name: total_runs, dtype: int64

In [ ]:
player_dismissed = delivery[delivery['player_dismissed'].notnull()]
bowler = player_dismissed.groupby('bowler')['player_dismissed'].count().sort_values(ascending=False).head()

bowler

bowler
SL Malinga         170
A Mishra           142
DJ Bravo           137
Harbhajan Singh    136
PP Chawla          133
Name: player_dismissed, dtype: int64

In [70]:
player_dismissed = delivery[delivery['player_dismissed'] != 'nan']
bowler = player_dismissed.groupby('bowler')['player_dismissed'].count().sort_values(ascending=False).head()

bowler

bowler
SL Malinga         170
A Mishra           142
DJ Bravo           137
Harbhajan Singh    136
PP Chawla          133
Name: player_dismissed, dtype: int64

In [71]:
# Sirf woh dismissals jo bowler ki profile mein jati hain
vaild_dismissals = ['caught', 'bowled', 'lbw', 'stumped', 'caught and bowled', 'hit wicket']

# Filter data
wicket_data = delivery[delivery['dismissal_kind'].isin(vaild_dismissals)]

# Ab count karein
real_wickets = wicket_data.groupby('bowler')['player_dismissed'].count().sort_values(ascending=False)

In [73]:
real_wickets.head()

bowler
SL Malinga         154
A Mishra           134
Harbhajan Singh    127
PP Chawla          126
DJ Bravo           122
Name: player_dismissed, dtype: int64

In [75]:
t_run = delivery.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head()
t_run

batsman
SK Raina     4548
V Kohli      4423
RG Sharma    4207
G Gambhir    4132
DA Warner    4014
Name: batsman_runs, dtype: int64

In [77]:
t_bowler = delivery[delivery['player_dismissed'].notnull()]
t_bowler

b = t_bowler.groupby('bowler')['player_dismissed'].count().sort_values(ascending=False).head()

In [78]:
b

bowler
SL Malinga         170
A Mishra           142
DJ Bravo           137
Harbhajan Singh    136
PP Chawla          133
Name: player_dismissed, dtype: int64

In [79]:
t_run = delivery[delivery['batsman_runs']==6]
bat_team = t_run.groupby('batting_team')['batsman_runs'].count().sort_values(ascending=False)

In [80]:
bat_team

batting_team
Royal Challengers Bangalore    935
Mumbai Indians                 876
Kings XI Punjab                762
Chennai Super Kings            742
Delhi Daredevils               686
Kolkata Knight Riders          659
Rajasthan Royals               538
Deccan Chargers                400
Sunrisers Hyderabad            364
Pune Warriors                  196
Gujarat Lions                  155
Rising Pune Supergiant          89
Rising Pune Supergiants         68
Kochi Tuskers Kerala            53
Name: batsman_runs, dtype: int64

In [81]:
over = delivery.groupby(['match_id', 'over'])['total_runs'].sum().sort_values(ascending=False).head()

In [82]:
over

match_id  over
22        15      49
388       1       47
283       3       46
516       6       46
2         20      45
Name: total_runs, dtype: int64