In [1]:
# Pandas Part 13 - The isin() function
#

In [2]:
import pandas as pd
delivery = pd.read_csv("deliveries.csv")
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [6]:
death_over=delivery[delivery['over']>15]

In [18]:
all_batsman=death_over.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(10)
# all_batsman[all_batsman>200].index
# all_batsman[all_batsman>200].values
# all_batsman[all_batsman>200].values.tolist()
# all_batsman[all_batsman>200].index.tolist()
x=all_batsman[all_batsman>200]
batsman_list = x.index.tolist()
batsman_list

['MS Dhoni',
 'KA Pollard',
 'RG Sharma',
 'YK Pathan',
 'RA Jadeja',
 'AB de Villiers',
 'V Kohli',
 'JP Duminy',
 'Yuvraj Singh',
 'IK Pathan']

In [21]:
final = delivery[delivery['batsman'].isin(batsman_list)]

In [22]:
final

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
66,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,11,5,Yuvraj Singh,MC Henriques,STR Binny,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
67,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,11,6,Yuvraj Singh,MC Henriques,STR Binny,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
69,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,12,2,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
70,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,12,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
72,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,12,5,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,0,0,0,V Kohli,bowled,NaN
150420,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,3,AB de Villiers,KL Rahul,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150422,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,5,AB de Villiers,KL Rahul,Bipul Sharma,0,...,0,0,0,0,0,0,0,AB de Villiers,caught,MC Henriques

In [23]:
runs = final.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False)
runs

batsman
V Kohli           4423
RG Sharma         4207
MS Dhoni          3560
AB de Villiers    3486
YK Pathan         2922
Yuvraj Singh      2591
KA Pollard        2354
JP Duminy         1993
RA Jadeja         1732
IK Pathan         1150
Name: batsman_runs, dtype: int64

In [24]:
balls = final.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False)
balls

batsman
V Kohli           3494
RG Sharma         3274
MS Dhoni          2680
AB de Villiers    2402
YK Pathan         2076
Yuvraj Singh      2050
KA Pollard        1674
JP Duminy         1634
RA Jadeja         1458
IK Pathan          985
Name: batsman_runs, dtype: int64

In [25]:
sr = (runs/balls)*100
sr

batsman
V Kohli           126.588437
RG Sharma         128.497251
MS Dhoni          132.835821
AB de Villiers    145.129059
YK Pathan         140.751445
Yuvraj Singh      126.390244
KA Pollard        140.621266
JP Duminy         121.970624
RA Jadeja         118.792867
IK Pathan         116.751269
Name: batsman_runs, dtype: float64

In [29]:
target_players = ['CH Gayle', 'MS Dhoni', 'RG Sharma']

mask = delivery['batsman'].isin(target_players)
top_players_data = delivery[mask]

print("Selected Players Data:")
top_players_data.groupby('batsman')['batsman_runs'].sum()

Selected Players Data:

batsman
CH Gayle     3651
MS Dhoni     3560
RG Sharma    4207
Name: batsman_runs, dtype: int64

In [28]:
# 4. NOT ISIN (~): Maan lijiye humein in 3 ke ILAWA baaki sab ka data chahiye
other_players_mask = ~delivery['batsman'].isin(target_players)
others_data = delivery[other_players_mask]

print("\nBaaki saare players ka count:")
print(others_data['batsman'].nunique())

Baaki saare players ka count:
458